### PR TITLE
TEL-3335 add step to canary to check dashboard availability

### PR DESCRIPTION
**Pull request by TimothyFothergill**
Co-authored-by: Matthew Hollick <22219356+matthew-hollick@users.noreply.github.com>

### CODE REVIEW

**Review by matthew-hollick — DISMISSED** [review]
Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.

**Review by matthew-hollick — DISMISSED** [review]
looks "wheely" good to me.

**Review by matthew-hollick — DISMISSED** [review]
thank you.
I hate it.

**Comment by TimothyFothergill** [comment]
Issues around dependency wheel following a vulnerability being found, resolved by specifying a minimum version of the latest and ensuring it's listed.

**Review by matthew-hollick — APPROVED** [review]
LGTM

**Pull request merged**
